name: mxonlive
description: Premium Live TV Player.
publish_to: 'none'
version: 4.8.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  url_launcher: ^6.2.6
  
  # UI
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  marquee: ^2.2.3
  flutter_spinkit: ^5.2.0
  
  # Player & System
  pod_player: ^0.2.2
  wakelock_plus: ^1.1.4
  
  # Analytics
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# Icon Config
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 23 # Updated SDK

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
